#!/bin/bash
echo -n "Enter the name of a file to inspect: "
read FILE;

#Greps out SSN number with Dash in between; 555-44-7777
echo $FILE
egrep "[0-9]{3}[-][0-9]{2}[-][0-9]{4}" $FILE

#Greps out SSN number with Space in between; 555 44 7777
echo $FILE
egrep "[0-9]{3}\s[0-9]{2}\s[0-9]{4}" $FILE

echo " Test complete."
